### ISSUE TITLE
Using "steal" causes freeze/crash on windows 10

### ISSUE THREAD

**Issue by whitephoenix0** [TheTechCloud/BlackInk#1]
Sometimes the window stops responding, sometimes the money count stops moving
While I'm at it, I'm going to suggest that you ditch the whole exe thing for now, it adds a lot of large files to the project and is really tricky to deal with. I suggest you remove the executables from the project and worry about that when you have more players. For now, I would just use .py files

**Comment by whitephoenix0** [comment]
http://effbot.org/zone/python-compile.htm Compiling python

**Comment by awkwardtechdude** [comment]
The Linux executable works fine on my system, so I'll leave it. The Win one will go.

**Comment by awkwardtechdude** [comment]
Also, would you like to join the team?

**Comment by awkwardtechdude** [comment]
Usually dev is the better branch to go to for submitting fixes, it's got less "inertia"

**Comment by whitephoenix0** [comment]
Sure, not sure how much I can contribute I can help a bit.
